project:
  type: website

website:
  title: "WHOAFRO/DPC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    theme: flatly           
    code-fold: true
    code-summary: "Show code"
    code-tools: false
    code-block-bg: true
    css: styles.css
    page-layout: full          # ← makes the report use full browser width
editor: visual
execute:
  echo: false
  warning: false
  message: false

